import type { ApiTouristGuide } from "./types";

/**
 * Local preview data for the tour guides grid (6 cards).
 * Replace with live API data by setting NEXT_PUBLIC_DIRECTUS_APP_URL and
 * leaving NEXT_PUBLIC_TOUR_GUIDES_USE_DUMMY unset or "false" — see `data.ts`.
 */
export const DUMMY_TOURIST_GUIDES: ApiTouristGuide[] = [
  {
    id: 9001,
    name: "أحمد العسيري",
    name_en: "Ahmed Al-Asiri",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    phone_number: "966501234567",
    whatsapp: "966501234567",
    content: null,
    content_en: null,
    description:
      "مرشد معتمد يختص بالجولات الثقافية في أبها والقرى التراثية، مع خبرة عشر سنوات.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "ذكر",
    arabic_language_level: "advanced",
    english_language_level: "intermediate",
    specializations: "السياحة الثقافية, الجبال, التراث",
    specializations_en: null,
    date: null,
    transportation: true,
  },
  {
    id: 9002,
    name: "نورة الغامدي",
    name_en: "Noura Al-Ghamdi",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    phone_number: "966507654321",
    whatsapp: "966507654321",
    content: null,
    content_en: null,
    description:
      "تقدم جولات عائلية وطرق آمنة لاستكشاف المزارع والحدائق في عسير.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "أنثى",
    arabic_language_level: "advanced",
    english_language_level: "advanced",
    specializations: "السياحة العائلية, الطبيعة",
    specializations_en: null,
    date: null,
    transportation: true,
  },
  {
    id: 9003,
    name: "خالد الشهري",
    name_en: "Khaled Al-Shehri",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
    phone_number: null,
    whatsapp: "966552223344",
    content: null,
    content_en: null,
    description: "متخصص في المشي لمسافات طويلة ومسارات جبلية معتمدة.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "ذكر",
    arabic_language_level: "advanced",
    english_language_level: "beginner",
    specializations: "المشي لمسافات طويلة, الجبال",
    specializations_en: null,
    date: null,
    transportation: false,
  },
  {
    id: 9004,
    name: "هند القحطاني",
    name_en: "Hind Al-Qahtani",
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    phone_number: "966599887766",
    whatsapp: "966599887766",
    content: null,
    content_en: null,
    description: "جولات تصوير وفنون وأسواق محلية مع شرح تاريخي للمواقع.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "أنثى",
    arabic_language_level: "advanced",
    english_language_level: "intermediate",
    specializations: "السياحة الثقافية, التصوير",
    specializations_en: null,
    date: null,
    transportation: false,
  },
  {
    id: 9005,
    name: "سعد الزهراني",
    name_en: "Saad Al-Zahrani",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    phone_number: "966544332211",
    whatsapp: "966544332211",
    content: null,
    content_en: null,
    description: "تنظيم رحلات جماعية وحافلات صغيرة لزيارة المعالم الرئيسية.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "ذكر",
    arabic_language_level: "intermediate",
    english_language_level: "intermediate",
    specializations: "الجولات الجماعية, المعالم السياحية",
    specializations_en: null,
    date: null,
    transportation: true,
  },
  {
    id: 9006,
    name: "ريم العتيبي",
    name_en: "Reem Al-Otaibi",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    phone_number: null,
    whatsapp: "966511223344",
    content: null,
    content_en: null,
    description: "تجارب طهي محلي وزيارات لمزارع القهوة والورود في المنطقة.",
    description_en: null,
    website: null,
    instagram: null,
    x_platform: null,
    tiktok: null,
    gender: "أنثى",
    arabic_language_level: "advanced",
    english_language_level: "advanced",
    specializations: "المطبخ المحلي, الطبيعة, السياحة العائلية",
    specializations_en: null,
    date: null,
    transportation: true,
  },
];
