import type { AseerCuisinePageData } from "./types";

/** Static English fallback when Directus is off — CMS should supply localized copy in production. */
export const ASEER_CUISINE_DUMMY_EN: AseerCuisinePageData = {
  hero: {
    videoUrl: "/assets/videos/aseer-cuisine-hero.mp4",
    posterImage: "/assets/community/hero-comunity-bg.png",
  },
  dishesSection: {
    title: "Taste traditional Aseeri dishes",
    description:
      "Aseeri cooking brings mountains, valleys, and farms together on one table: coffee from highland beans, dates from Bisha, mountain wheat and valley grains, fresh dairy, and wildflower honey—often finishing with slow-cooked haneeth from local herds. Explore dishes like haneeth, areekah, mashgothah, asidah, mifa bread from the tannur, marqoush bread, mabthoothah, and more.",
    cards: [
      {
        id: "dish-1",
        title: "Haneeth",
        image: "/assets/community/hero-comunity-bg.png",
      },
      {
        id: "dish-2",
        title: "Areekah",
        image: "/assets/community/hero-comunity-bg.png",
      },
      {
        id: "dish-3",
        title: "Mashgothah",
        image: "/assets/community/hero-comunity-bg.png",
      },
      {
        id: "dish-4",
        title: "Asidah",
        image: "/assets/community/hero-comunity-bg.png",
      },
    ],
  },
  restaurantsSection: {
    title: "Popular restaurants",
    ctaLabel: "Restaurants",
    ctaHref: "/restaurants",
    cards: [
      {
        id: "r-1",
        image: "/assets/community/hero-comunity-bg.png",
        title: "Haneeth House",
        location: "Abha — King Fahd Road",
        cuisineType: "Aseeri cuisine",
        priceRange: "SAR 50–120",
        rating: 4.8,
        reviewsCount: 542,
      },
      {
        id: "r-2",
        image: "/assets/community/hero-comunity-bg.png",
        title: "Areekah Corner",
        location: "Khamis Mushait — Airport district",
        cuisineType: "Casual dining",
        priceRange: "SAR 35–90",
        rating: 4.6,
        reviewsCount: 389,
      },
      {
        id: "r-3",
        image: "/assets/community/hero-comunity-bg.png",
        title: "Mifa Bakery",
        location: "Tanomah — Souq Street",
        cuisineType: "Aseeri baking",
        priceRange: "SAR 25–70",
        rating: 4.7,
        reviewsCount: 261,
      },
      {
        id: "r-4",
        image: "/assets/community/hero-comunity-bg.png",
        title: "House of Marqoush",
        location: "Al-Namas — King Khalid Road",
        cuisineType: "Heritage food",
        priceRange: "SAR 40–110",
        rating: 4.5,
        reviewsCount: 317,
      },
      {
        id: "r-5",
        image: "/assets/community/hero-comunity-bg.png",
        title: "Marsa Aseer",
        location: "Bisha — city centre",
        cuisineType: "Local plates",
        priceRange: "SAR 30–85",
        rating: 4.4,
        reviewsCount: 198,
      },
      {
        id: "r-6",
        image: "/assets/community/hero-comunity-bg.png",
        title: "Mountain Table",
        location: "Rijal Almaa — historic quarter",
        cuisineType: "Highland kitchen",
        priceRange: "SAR 60–140",
        rating: 4.9,
        reviewsCount: 476,
      },
    ],
  },
  localFlavorsSection: {
    title: "Local flavours",
    subtitle: "A window into Aseer’s most distinctive tastes",
    cards: [
      { id: "flavor-1", title: "Haneeth", image: "/restaurant/img1.png" },
      { id: "flavor-2", title: "Areekah", image: "/restaurant/img2.png" },
      { id: "flavor-3", title: "Mashgothah", image: "/restaurant/img3.png" },
      { id: "flavor-4", title: "Mifa bread", image: "/restaurant/img4.png" },
    ],
  },
  cookingExperiencesSection: {
    title: "Cooking experiences",
    description:
      "Join hands-on sessions with local hosts: from haneeth and tannur bread to coffee roasting and mountain honey—built around the same ingredients that define Aseeri tables.",
    ctaLabel: "View all experiences",
    ctaHref: "/experiences",
    cards: [
      {
        id: "cook-exp-1",
        imageUrl: "/restaurant/img1.png",
        category: "Cooking",
        title: "Cook haneeth the Aseeri way",
        duration: "3 hours",
        description:
          "Choose cuts, rubs, and slow-cooking steps for authentic Aseeri haneeth.",
        provider: "Bayt Al Nakaat",
        price: 180,
        currency: "SAR",
        groupSize: 6,
        bookUrl: "#",
      },
      {
        id: "cook-exp-2",
        imageUrl: "/restaurant/img2.png",
        category: "Heritage baking",
        title: "Mifa bread workshop",
        duration: "2.5 hours",
        description:
          "Mix, shape, and bake mifa bread using traditional tannur methods.",
        provider: "Heritage Aseer Kitchen",
        price: 120,
        currency: "SAR",
        groupSize: 8,
        bookUrl: "#",
      },
      {
        id: "cook-exp-3",
        imageUrl: "/restaurant/img3.png",
        category: "Sweets",
        title: "Areekah & mashgothah",
        duration: "2 hours",
        description:
          "Interactive prep and plating for two beloved Aseeri comfort dishes.",
        provider: "Pioneers of Taste",
        price: 95,
        currency: "SAR",
        groupSize: 10,
        bookUrl: "#",
      },
      {
        id: "cook-exp-4",
        imageUrl: "/restaurant/img4.png",
        category: "Coffee & honey",
        title: "Aseeri coffee circle",
        duration: "1.5 hours",
        description:
          "Roast, brew, and taste local coffee with honey and Bisha dates.",
        provider: "Mountain Coffee",
        price: 75,
        currency: "SAR",
        groupSize: 12,
        bookUrl: "#",
      },
    ],
  },
  chefsVideoSection: {
    title: "Meet Aseer’s chefs",
    subtitle: "Stories from the kitchens that carry the region’s flavours forward",
    videoUrl: "/assets/videos/aseer-cuisine-chefs.mp4",
    posterImage: "/restaurant/img4.png",
  },
};
