import type { Landmark } from "@/components/landmarks/data";

/** Static rows when Directus returns no attractions (main `/attractions` listing). */
export const FALLBACK_ATTRACTIONS: Landmark[] = [
  {
    id: "a-1",
    title: "سوق الثلاثاء",
    location: "أبها",
    area: "أبها",
    description: "تسلق جبل سودا مع متسلق الجبال المحلي فيصل",
    guideName: "فيصل",
    image: "/restaurant/img1.png",
    cityId: "abha",
    travelerTypes: ["solo", "couple"],
    priceFrom: 0,
    priceTo: 30,
    interestTags: ["historical", "culture", "shopping"],
  },
  {
    id: "a-2",
    title: "قرية رجال ألمع",
    location: "رجال ألمع",
    area: "محايل عسير",
    description: "استكشاف الفن المعماري التراثي في جولة ثقافية",
    guideName: "سارة",
    image: "/restaurant/img2.png",
    cityId: "mahayil",
    travelerTypes: ["couple", "family"],
    priceFrom: 50,
    priceTo: 120,
    interestTags: ["historical", "culture"],
  },
  {
    id: "a-3",
    title: "جبال السودة",
    location: "حديقة السودة ، أبها",
    area: "أبها",
    description: "مغامرة مشي في الطبيعة واستمتاع بالإطلالة",
    guideName: "محمد",
    image: "/restaurant/img3.png",
    cityId: "abha",
    travelerTypes: ["solo", "small-group", "large-group"],
    priceFrom: 20,
    priceTo: 220,
    interestTags: ["nature", "adventure"],
  },
  {
    id: "a-4",
    title: "قصر أبو سراح",
    location: "أبها",
    area: "أبها",
    description: "زيارة القصور التاريخية مع تجربة تراثية متكاملة",
    guideName: "أحمد",
    image: "/assets/attractions/attractions-hero.png",
    cityId: "abha",
    travelerTypes: ["family", "large-group"],
    priceFrom: 60,
    priceTo: 180,
    interestTags: ["historical", "culture"],
  },
  {
    id: "a-5",
    title: "منتزه الحبلة",
    location: "الحبلة",
    area: "أبها",
    description: "تجربة التلفريك والمناظر الجبلية الخلابة",
    guideName: "نورة",
    image: "/restaurant/img4.png",
    cityId: "abha",
    travelerTypes: ["couple", "family", "small-group"],
    priceFrom: 70,
    priceTo: 260,
    interestTags: ["nature", "adventure"],
  },
  {
    id: "a-6",
    title: "منتزه أبو خيال",
    location: "أبها",
    area: "أبها",
    description: "جلسات طبيعية وممرات للمشي وإطلالات بانورامية",
    guideName: "ليان",
    image: "/restaurant/img2.png",
    cityId: "abha",
    travelerTypes: ["family", "small-group"],
    priceFrom: 0,
    priceTo: 40,
    interestTags: ["nature", "relaxation"],
  },
  {
    id: "a-7",
    title: "قرية آل يوسف التراثية",
    location: "محايل عسير",
    area: "محايل عسير",
    description: "مشي بين البيوت الحجرية والممرات الضيقة مع شرح تراثي",
    guideName: "فهد",
    image: "/restaurant/img3.png",
    cityId: "mahayil",
    travelerTypes: ["couple", "family"],
    priceFrom: 0,
    priceTo: 50,
    interestTags: ["culture", "historical"],
  },
  {
    id: "a-8",
    title: "متحف محايل الشعبي",
    location: "محايل عسير",
    area: "محايل عسير",
    description: "قطع أثرية وقصص من حياة المنطقة عبر العصور",
    guideName: "لينا",
    image: "/restaurant/img1.png",
    cityId: "mahayil",
    travelerTypes: ["solo", "family"],
    priceFrom: 10,
    priceTo: 40,
    interestTags: ["historical", "culture"],
  },
];
